baseURL: https://sjha2048.github.io
theme: charlolamode
copyright: "Built with ❤️ by [sjha2048](https://github.com/sjha2048) using [charlolamode](https://github.com/charlola/hugo-theme-charlolamode)"
