baseURL: https://sjha2048.github.io
theme: charlolamode
title: charlola.mode
paginate: 5
copyright: "Built with ❤️ by [sjha2048](https://github.com/sjha2048) using [charlolamode](https://github.com/charlola/hugo-theme-charlolamode)"


menu:
    main:
        - name: Contact
          url: /contact/
          weight: 30
        - name: Articles
          url: /articles/
          weight: 20
        - name: Projects
          url: /projects/
          weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Author's Name


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Sahil Jha
        description: |

          Hello, I am Sahil.
           I am a software engineer. 
        

          having strong foundation in computer science and a love for solving complex problems and experimenting with new technologies.
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: twitter
          url: "https://twitter.com/sjha2048"
        - name: github
          url: "https://github.com/sjha2048"
        - name: linkedin
          url: "https://www.linkedin.com/in//"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true


minify:
    disableXML: true


